version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres:
